[project]
name = "merkle-listen"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.merkle-validator]
path = "contracts/merkle-validator.clar"
depends_on = []

[contracts.event-listener]
path = "contracts/event-listener.clar"
depends_on = []

[contracts.proof-manager]
path = "contracts/proof-manager.clar"
depends_on = []

[contracts.signature-verifier]
path = "contracts/signature-verifier.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
